STARTUP_TRIM_SECONDS = 0.6

# "red", "infrared", "red_infrared_mean", "none"
CHANNEL_SUBTRACTION = "none"
INVERT_PROCESSED_SIGNAL = False
SAMPLING_FREQUENCY_HZ = 100

# "highpass", "lowpass", "bandpass", "none"
FILTER_TYPE = "bandpass"
LOWER_CUTOFF_FREQUENCY_HZ = 0.5
UPPER_CUTOFF_FREQUENCY_HZ = 8.0
FILTER_COEFFICIENT_COUNT = 401
FILTER_WINDOW_TYPE = "hamming"

# "none", "robust_z_score", "min_max"
NORMALIZATION_TYPE="robust_z_score"

# Experimental part
ARTIFACT_DETECTION_ENABLED = False
SHOW_ARTIFACTS_ON_PLOT = True
ARTIFACT_JUMP_THRESHOLD_FACTOR = 8.0
ARTIFACT_PADDING_SECONDS = 0.5
RANGE_ARTIFACT_DETECTION_ENABLED = True
ARTIFACT_RANGE_WINDOW_SECONDS = 0.5
ARTIFACT_RANGE_THRESHOLD_FACTOR = 6.0