STARTUP_TRIM_SECONDS = 0.6000000238418579
INVERT_PROCESSED_SIGNAL = True

CHANNEL_SUBTRACTION = 'none'

DC_REMOVAL_ENABLED = True
# "causal" or "centered"
DC_REMOVAL_WINDOW_TYPE = 'centered'
DC_REMOVAL_WINDOW_SECONDS = 2.0

HIGH_PASS_FILTER_ENABLED = True
HIGH_PASS_CUTOFF_HZ = 0.6999999284744263
HIGH_PASS_FILTER_PASSES = 1

LOW_PASS_FILTER_ENABLED = True
LOW_PASS_CUTOFF_HZ = 5.0
LOW_PASS_FILTER_PASSES = 1
