STARTUP_TRIM_SECONDS = 0.6
INVERT_PROCESSED_SIGNAL = True

CHANNEL_SUBTRACTION = "red"

DC_REMOVAL_ENABLED = True
DC_REMOVAL_WINDOW_TYPE = "centered" # "causal" or "centered"
DC_REMOVAL_WINDOW_SECONDS = 2.0

HIGH_PASS_FILTER_ENABLED = True
HIGH_PASS_CUTOFF_HZ = 0.7
HIGH_PASS_FILTER_PASSES = 1

LOW_PASS_FILTER_ENABLED = False
LOW_PASS_CUTOFF_HZ = 5.0
LOW_PASS_FILTER_PASSES = 1